### ISSUE TITLE
Applying a transformation to `train` but not `test`

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaAI/MLJModelInterface.jl#146]
Apologies if this has been asked before, but I was wondering whether it is possible for me to use SMOTE via [Resample.jl](https://github.com/rikhuijzer/resample.jl) in such a way that evaluations occur on the `test` set and not on the `train` set. More specifically, can I use `MLJ.evaluate` in such a way that SMOTE is applied before training the model, but **not** before testing the model. Currently, I'm evaluating my model on `test` data with synthetic samples which might give me wrong results because the model overfits on the "fake" data.

**Comment by ablaom** [comment]
Perhaps I misunderstand the question but perhaps my [suggestion](https://github.com/alan-turing-institute/MLJ.jl/issues/661#issue-705225473) addresses your query. In the mode wrapper  I propose, the oversampling is only performed "internally" for the sake of training.

**Comment by rikhuijzer** [comment]
Ah yes. I forgot that there was an example there. Thanks! Trying to implement it in `Resample.jl` now

**Comment by ablaom** [comment]
If you are making a general purpose wrapper, change the `@node f(X)` calls to `node(f, X)` and wrap your learning network in a fit method ([Method II](https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/#Method-II:-Finer-control-(advanced)) in the manual).
