### ISSUE TITLE
Fix axis ordering in UnivariateFinite example

### ISSUE THREAD

**Issue by jeremiedb** [JuliaAI/MLJModelInterface.jl#53]
In docs, it seems like the axis order in the doc as been reversed: https://github.com/alan-turing-institute/MLJModelInterface.jl/blob/a064ba36cd5474a88e09a907401e8d891301462e/src/data_utils.jl#L393

The provided example fails: 

```julia
v = categorical([:x, :x, :y, :x, :z, :w])
probs = rand(3, 100)
probs = probs ./ sum(probs, dims=1)
UnivariateFinite([:x, :y, :z], probs, pool=v)
```

While the adjusted example with observation being a row works: 
```julia
v = categorical([:x, :x, :y, :x, :z, :w])
probs = rand(100, 3)
probs = probs ./ sum(probs, dims=2)
UnivariateFinite([:x, :y, :z], probs, pool=v)
```

**Comment by ablaom** [comment]
Yes, indeed. The docs are wrong. Good catch, thanks!

**Comment by ablaom** [comment]
Done already
@OkonSamuel
