### ISSUE TITLE
Roadmap to 1.0?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaAI/MLJModelInterface.jl#69]
There are only two packages that are required in order to implement the MLJ interface: ScientificTypes.jl and MLJModelInterface.jl.

We now have a 1.0 release of ScientificTypes.jl. 🎉 

Would it be feasible to make a 1.0 release of MLJModelInterface?

**Comment by DilumAluthge** [comment]
There are several experimental APIs, but I think it is fine to make breaking changes to an experimental API in a non-breaking release.

See my comment here: https://github.com/alan-turing-institute/MLJ.jl/pull/648#issuecomment-683360181

**Comment by ablaom** [comment]
Yeah, I think once https://github.com/alan-turing-institute/MLJModels.jl/issues/355 is sorted, we could move to 1.0.

**Comment by DilumAluthge** [comment]
Bump @ablaom @tlienart
